version: 2

models:
    - name: staging
      database: possible-lotus-375803
      schema: trips_data_all

      tables:
        - name: fhvtripdata
        - name: greentripdata
        - name: yellowtripdata